name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --name test --onefile --specpath . main.py data_preparation.py evaluate_model.py generate_synthetic_data.py train_model.py

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

      - name: Create Tag
        run: git tag -a v1.0 -m "Version 1.0" && git push origin v1.0

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "dist/*,synthetic_real_estate_data.csv"
          bodyFile: "body.md"
